---
language: node_js

sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install ember-cli@$EMBER_CLI_VERSION
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test

env:
  - EMBER_CLI_VERSION=0.0.46
  - EMBER_CLI_VERSION=0.0.999